name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        cd client
        yarn install
        yarn build
        cd ../server
        yarn install
        yarn run build
        cd ..
    
    - name: Commit Files
      run: |
        mv ./server/dist ./serverbuild
        mv ./server/package.json ./package.json
        mv ./server/yarn.lock ./yarn.lock
        mv ./client/dist ./clientbuild
        rm -rf ./client
        rm -rf ./server
        git add *
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Add dist"

    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: deploy
        force: true
